%% =========================================================================
%  SECTION 9 — PLOTTING
%
%  Figure 1: Altitude and TAS vs mission time
%  Figure 2: Throttle vs mission time
% =========================================================================

% Colour table: dynamically sized to cover full mission distance
band_km           = 100;
total_dist_km_pre = (d_climb_m + d_cruise_m + d_desc_m) / 1e3;
n_bands_needed    = ceil(total_dist_km_pre / band_km);

colour_base = [
    0.50, 0.00, 0.75;   % purple
    0.00, 0.20, 0.90;   % blue
    0.00, 0.80, 0.90;   % cyan
    0.00, 0.65, 0.10;   % green
    0.95, 0.85, 0.00;   % yellow
    1.00, 0.50, 0.00;   % orange
    0.90, 0.00, 0.00;   % red
];

if n_bands_needed <= size(colour_base,1)
    colour_rgb = colour_base(1:n_bands_needed, :);
else
    colour_rgb = colour_base(mod((0:n_bands_needed-1), size(colour_base,1))+1, :);
end

n_bands = n_bands_needed;

% Build global mission vectors
t_plot_clmb = t_clmb_min;
h_plot_clmb = h_clmb;
V_plot_clmb = V_clmb;
d_plot_clmb = dx_clmb / 1e3;

t_plot_cr = t_climb_min + t_cr_rel;
h_plot_cr = h_cruise * ones(1, n_cr);
V_plot_cr = V_cruise * ones(1, n_cr);
d_plot_cr = (d_climb_m + linspace(0, d_cruise_m, n_cr)) / 1e3;

t_plot_dc = t_climb_min + t_cruise_min + t_dc_rel;
h_plot_dc = h_dc_vec;
V_plot_dc = V_descent * ones(1, n_dc);
d_plot_dc = (d_climb_m + d_cruise_m + linspace(0, d_desc_m, n_dc)) / 1e3;

t_all = [t_plot_clmb, t_plot_cr, t_plot_dc];
h_all = [h_plot_clmb, h_plot_cr, h_plot_dc];
V_all = [V_plot_clmb, V_plot_cr, V_plot_dc];
d_all = [d_plot_clmb, d_plot_cr, d_plot_dc];

t_cr_global = t_climb_min + t_cr_rel;
t_dc_global = t_climb_min + t_cruise_min + t_dc_rel;

%% Figure 1: Altitude and TAS vs Time

fig1 = figure('Name','Snowrunner 670 Reference Mission: Airspeed and Altitude', ...
    'Units','inches', ...
    'Position',[1 1 9.5 5.5], ...
    'Color','w');

yyaxis left
hold on; grid on; box on;

for b = 1:n_bands
    d_lo = (b-1) * band_km;
    d_hi = b * band_km;

    in_b = d_all >= d_lo & d_all <= d_hi;
    idx = find(in_b);

    if isempty(idx)
        continue;
    end

    idx_ext = unique([max(1,idx(1)-1), idx(:)', min(numel(d_all),idx(end)+1)]);

    plot(t_all(idx_ext), h_all(idx_ext), '-', ...
        'Color', colour_rgb(b,:), ...
        'LineWidth', 2.8);
end

ylabel('Altitude, $h$ [m]', ...
    'FontSize',12, ...
    'Color','k', ...
    'Interpreter','latex');

ylim([0, h_cruise * 1.22]);
set(gca, 'YColor','k');

yyaxis right
hold on;

for b = 1:n_bands
    d_lo = (b-1) * band_km;
    d_hi = b * band_km;

    in_b = d_all >= d_lo & d_all <= d_hi;
    idx = find(in_b);

    if isempty(idx)
        continue;
    end

    idx_ext = unique([max(1,idx(1)-1), idx(:)', min(numel(d_all),idx(end)+1)]);

    plot(t_all(idx_ext), V_all(idx_ext), '--', ...
        'Color', colour_rgb(b,:), ...
        'LineWidth', 1.8);
end

ylabel('True Airspeed [m/s]', ...
    'FontSize',12, ...
    'Color','k', ...
    'Interpreter','none');

ylim([0, V_climb * 1.9]);
set(gca, 'YColor','k');

% Phase boundary lines and labels
yyaxis left

xline(t_climb_min, 'k:', ...
    'LineWidth',1.5, ...
    'HandleVisibility','off');

xline(t_climb_min + t_cruise_min, 'k:', ...
    'LineWidth',1.5, ...
    'HandleVisibility','off');

text(t_climb_min * 0.45, h_cruise * 0.40, 'CLIMB', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color',[0.3 0.3 0.3], ...
    'HorizontalAlignment','center', ...
    'Interpreter','none');

text(t_climb_min + t_cruise_min * 0.50, h_cruise * 1.11, 'CRUISE', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color',[0.3 0.3 0.3], ...
    'HorizontalAlignment','center', ...
    'Interpreter','none');

text(t_climb_min + t_cruise_min + t_desc_min * 0.50, h_cruise * 0.40, 'DESCENT', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color',[0.3 0.3 0.3], ...
    'HorizontalAlignment','center', ...
    'Interpreter','none');

xlabel('Mission Time, $t$ [min]', ...
    'FontSize',12, ...
    'Interpreter','latex');

xlim([0, t_all(end) * 1.02]);

title('Reference Mission: True Airspeed and Altitude vs Time', ...
    'FontSize',12, ...
    'Interpreter','none');

% Distance legend
total_dist_km = d_all(end);
leg_h = gobjects(n_bands,1);
leg_lbl = cell(n_bands,1);

for b = 1:n_bands
    d_lo = (b-1) * band_km;

    if d_lo >= total_dist_km
        break;
    end

    yyaxis left

    leg_h(b) = plot(nan, nan, '-', ...
        'Color', colour_rgb(b,:), ...
        'LineWidth',3.5);

    leg_lbl{b} = sprintf('%d - %d km', d_lo, b * band_km);
end

valid_idx = arrayfun(@(x) isgraphics(x,'line'), leg_h);

lg = legend(leg_h(valid_idx), leg_lbl(valid_idx), ...
    'Location','eastoutside', ...
    'FontSize',9);

lg.Title.String = 'Cumulative distance';

% Save Figure 1 immediately using its handle
set(fig1, 'Renderer','painters');
exportgraphics(fig1, 'RefMission1.png', 'Resolution',600);

%% Figure 2: Throttle vs Time

fig2 = figure('Name','Snowrunner 670 Reference Mission: Throttle Profile', ...
    'Units','inches', ...
    'Position',[1 1 9.5 7.0], ...
    'Color','w');

% Subplot 1: Climb
subplot(3,1,1)

plot(t_plot_clmb, thr_clmb_pct, '-', ...
    'Color',[0.10 0.30 0.85], ...
    'LineWidth',2.5);

hold on; grid on; box on;

yline(100, 'k--', ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

ylabel('Throttle [%]', ...
    'FontSize',11, ...
    'Interpreter','none');

title(sprintf('Climb | V_T_A_S = %.0f m/s | Full Throttle | Avg ROC = %.1f m/s (%.0f fpm)', ...
    V_climb, ROC_avg_ms, ROC_avg_fpm), ...
    'FontSize',10, ...
    'Interpreter','none');

ylim([0, 125]);
xlim([t_plot_clmb(1), t_plot_clmb(end)]);

text(mean(t_plot_clmb), 52, ...
    sprintf('Climb time: %.1f min | d_climb = %.1f km (%.1f nmi)', ...
    t_climb_min, d_climb_m/1e3, d_climb_m/1852), ...
    'FontSize',9, ...
    'HorizontalAlignment','center', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.7 0.7 0.7], ...
    'Interpreter','none');

% Subplot 2: Cruise
subplot(3,1,2)

plot(t_cr_global, thr_cr_pct, '-', ...
    'Color',[0.82 0.15 0.08], ...
    'LineWidth',2.5);

grid on; box on;

ylabel('Throttle [%]', ...
    'FontSize',11, ...
    'Interpreter','none');

title(sprintf('Cruise | V_T_A_S = %.0f m/s | h = %.0f m | L/D = %.2f', ...
    V_cruise, h_cruise, LD_cruise), ...
    'FontSize',10, ...
    'Interpreter','none');

y_max_cr = max(thr_cr_pct) * 1.35;
ylim([0, y_max_cr]);
xlim([t_cr_global(1), t_cr_global(end)]);

text(mean(t_cr_global), max(thr_cr_pct) * 0.40, ...
    sprintf('W_start = %.0f kg -> W_end = %.0f kg | d_cruise = %.0f km (%.0f nmi)', ...
    W3_kg, W4_kg, d_cruise_km, d_cruise_nmi), ...
    'FontSize',9, ...
    'HorizontalAlignment','center', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.7 0.7 0.7], ...
    'Interpreter','none');

% Subplot 3: Descent
subplot(3,1,3)

plot(t_dc_global, thr_dc_pct, '-', ...
    'Color',[0.05 0.60 0.10], ...
    'LineWidth',2.5);

grid on; box on;

xlabel('Mission Time [min]', ...
    'FontSize',11, ...
    'Interpreter','none');

ylabel('Throttle [%]', ...
    'FontSize',11, ...
    'Interpreter','none');

title(sprintf('Descent | V_T_A_S = %.1f m/s | V_horiz = %.0f m/s | ROD = %.0f fpm', ...
    V_descent, V_horiz_req, ROD_fpm), ...
    'FontSize',10, ...
    'Interpreter','none');

y_max_dc = max(max(thr_dc_pct) * 1.35, 5.0);
ylim([0, y_max_dc]);
xlim([t_dc_global(1), t_dc_global(end)]);

if max(thr_dc_pct) < 0.10
    text(mean(t_dc_global), y_max_dc * 0.50, ...
        'Power-off glide: gravity alone sustains the required descent profile', ...
        'FontSize',9, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor','w', ...
        'EdgeColor',[0.7 0.7 0.7], ...
        'Interpreter','none');
else
    text(mean(t_dc_global), max(thr_dc_pct) * 0.35, ...
        sprintf('Throttle required: natural glide is steeper than %.0f fpm / %.0f m/s horizontal', ...
        ROD_fpm, V_horiz_req), ...
        'FontSize',9, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor','w', ...
        'EdgeColor',[0.7 0.7 0.7], ...
        'Interpreter','none');
end

sgtitle('Reference Mission Throttle Profile', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'Interpreter','none');

% Save Figure 2 using its handle
set(fig2, 'Renderer','painters');
exportgraphics(fig2, 'RefMission2.png', 'Resolution',600);